language: bash
services: docker
sudo: required

env:
  - IMAGE: tdmproject/tdmq-notebook

install:
  - make images IMAGE=${IMAGE}

script:
  - docker run -it --rm --entrypoint "" $IMAGE bash -l -c "python3 -c 'import tiledb'"
  - docker-compose up -d
  - docker exec datanode bash -c 'until datanode_cid; do sleep 0.1; done'


deploy:
  - provider: script
    script: bash push.sh
    on:
      repo: tdm-project/tdmq-notebook
      branch: master
