language: bash
services: docker
sudo: required

env:
  - IMAGE: tdmproject/tdmq-notebook

install:
  - make images

script:
  - docker run -it --rm $IMAGE bash -l -c "python3 -c 'import tiledb'"
  - docker run -it --rm $IMAGE bash -l -c "hdfs --help"


deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      repo: tdm-project/tdmq-notebook
      branch: master
